const Stories = [
    {
      story_id: 101,
      id: 111,
      place_name: 'Eiffel Tower',
      place_intro: 'The Eiffel Tower, an iconic symbol of Paris, stands as a testament to architectural marvel. With its intricate iron lattice structure, it offers breathtaking panoramic views of the City of Lights. Explore its rich history and romantic ambiance.',
      photo_count: 73,
      like_count: 48,
      date: '3rd February, 2020',
    },
    {
      story_id: 102,
      id: 112,
      place_name: 'Machu Picchu',
      place_intro: 'Machu Picchu, nestled high in the Andes mountains, is an ancient Inca citadel shrouded in mystery. Wander through its ancient ruins, where llamas roam freely, and soak in the spiritual energy of this UNESCO World Heritage site.',
      photo_count: 89,
      like_count: 72,
      date: '3rd February, 2020',
    },
    {
      story_id: 103,
      id: 113,
      place_name: 'Great Wall of China',
      place_intro: 'The Great Wall of China, a marvel of human engineering, stretches over 13,000 miles. Discover its history as a defense barrier and explore its stunning sections amidst picturesque landscapes. A true wonder of the world.',
      photo_count: 64,
      like_count: 51,
      date: '3rd February, 2020',
    },
    {
      story_id: 104,
      id: 114,
      place_name: 'Santorini',
      place_intro: 'Santorini, a Greek paradise in the Aegean Sea, boasts white-washed buildings perched on cliffs overlooking crystal-clear waters. Explore charming villages, savor local cuisine, and witness captivating sunsets over the caldera.',
      photo_count: 79,
      like_count: 67,
      date: '3rd February, 2020',
    },
    {
      story_id: 105,
      id: 115,
      place_name: 'Pyramids of Giza',
      place_intro: 'The Pyramids of Giza, Egypt\'s ancient wonders, have stood the test of time for over 4,000 years. Marvel at the colossal structures built as tombs for pharaohs and immerse yourself in the mysteries of ancient Egypt.',
      photo_count: 56,
      like_count: 40,
      date: '3rd February, 2020',
    },
    {
      story_id: 106,
      id: 111,
      place_name: 'Machu Picchu',
      place_intro: 'Machu Picchu, nestled high in the Andes mountains, is an ancient Inca citadel shrouded in mystery. Wander through its ancient ruins, where llamas roam freely, and soak in the spiritual energy of this UNESCO World Heritage site.',
      photo_count: 70,
      like_count: 58,
      date: '3rd February, 2020',
    },
    {
      story_id: 107,
      id: 112,
      place_name: 'Great Wall of China',
      place_intro: 'The Great Wall of China, a marvel of human engineering, stretches over 13,000 miles. Discover its history as a defense barrier and explore its stunning sections amidst picturesque landscapes. A true wonder of the world.',
      photo_count: 95,
      like_count: 61,
      date: '3rd February, 2020',
    },
    {
      story_id: 108,
      id: 113,
      place_name: 'Santorini',
      place_intro: 'Santorini, a Greek paradise in the Aegean Sea, boasts white-washed buildings perched on cliffs overlooking crystal-clear waters. Explore charming villages, savor local cuisine, and witness captivating sunsets over the caldera.',
      photo_count: 67,
      like_count: 79,
      date: '3rd February, 2020',
    },
    {
      story_id: 109,
      id: 114,
      place_name: 'Pyramids of Giza',
      place_intro: 'The Pyramids of Giza, Egypt\'s ancient wonders, have stood the test of time for over 4,000 years. Marvel at the colossal structures built as tombs for pharaohs and immerse yourself in the mysteries of ancient Egypt.',
      photo_count: 43,
      like_count: 32,
      date: '3rd February, 2020',
    },
    {
      story_id: 110,
      id: 115,
      place_name: 'Eiffel Tower',
      place_intro: 'The Eiffel Tower, an iconic symbol of Paris, stands as a testament to architectural marvel. With its intricate iron lattice structure, it offers breathtaking panoramic views of the City of Lights. Explore its rich history and romantic ambiance.',
      photo_count: 62,
      like_count: 45,
      date: '3rd February, 2020',
    },
    {
      story_id: 111,
      id: 111,
      place_name: 'Great Wall of China',
      place_intro: 'The Great Wall of China, a marvel of human engineering, stretches over 13,000 miles. Discover its history as a defense barrier and explore its stunning sections amidst picturesque landscapes. A true wonder of the world.',
      photo_count: 84,
      like_count: 70,
      date: '3rd February, 2020',
    },
    {
      story_id: 112,
      id: 112,
      place_name: 'Santorini',
      place_intro: 'Santorini, a Greek paradise in the Aegean Sea, boasts white-washed buildings perched on cliffs overlooking crystal-clear waters. Explore charming villages, savor local cuisine, and witness captivating sunsets over the caldera.',
      photo_count: 58,
      like_count: 42,
      date: '3rd February, 2020',
    },
    {
      story_id: 113,
      id: 113,
      place_name: 'Pyramids of Giza',
      place_intro: 'The Pyramids of Giza, Egypt\'s ancient wonders, have stood the test of time for over 4,000 years. Marvel at the colossal structures built as tombs for pharaohs and immerse yourself in the mysteries of ancient Egypt.',
      photo_count: 72,
      like_count: 53,
      date: '3rd February, 2020',
    },
    {
      story_id: 114,
      id: 114,
      place_name: 'Eiffel Tower',
      place_intro: 'The Eiffel Tower, an iconic symbol of Paris, stands as a testament to architectural marvel. With its intricate iron lattice structure, it offers breathtaking panoramic views of the City of Lights. Explore its rich history and romantic ambiance.',
      photo_count: 63,
      like_count: 49,
      date: '3rd February, 2020',
    },
    {
      story_id: 115,
      id: 115,
      place_name: 'Machu Picchu',
      place_intro: 'Machu Picchu, nestled high in the Andes mountains, is an ancient Inca citadel shrouded in mystery. Wander through its ancient ruins, where llamas roam freely, and soak in the spiritual energy of this UNESCO World Heritage site.',
      photo_count: 87,
      like_count: 71,
      date: '3rd February, 2020',
    },
    {
      story_id: 116,
      id: 111,
      place_name: 'Santorini',
      place_intro: 'Santorini, a Greek paradise in the Aegean Sea, boasts white-washed buildings perched on cliffs overlooking crystal-clear waters. Explore charming villages, savor local cuisine, and witness captivating sunsets over the caldera.',
      photo_count: 68,
      like_count: 55,
      date: '3rd February, 2020',
    },
    {
      story_id: 117,
      id: 112,
      place_name: 'Pyramids of Giza',
      place_intro: 'The Pyramids of Giza, Egypt\'s ancient wonders, have stood the test of time for over 4,000 years. Marvel at the colossal structures built as tombs for pharaohs and immerse yourself in the mysteries of ancient Egypt.',
      photo_count: 79,
      like_count: 63,
      date: '3rd February, 2020',
    },
    {
      story_id: 118,
      id: 113,
      place_name: 'Eiffel Tower',
      place_intro: 'The Eiffel Tower, an iconic symbol of Paris, stands as a testament to architectural marvel. With its intricate iron lattice structure, it offers breathtaking panoramic views of the City of Lights. Explore its rich history and romantic ambiance.',
      photo_count: 54,
      like_count: 47,
      date: '3rd February, 2020',
    },
    {
      story_id: 119,
      id: 114,
      place_name: 'Machu Picchu',
      place_intro: 'Machu Picchu, nestled high in the Andes mountains, is an ancient Inca citadel shrouded in mystery. Wander through its ancient ruins, where llamas roam freely, and soak in the spiritual energy of this UNESCO World Heritage site.',
      photo_count: 66,
      like_count: 54,
      date: '3rd February, 2020',
    },
    {
      story_id: 120,
      id: 115,
      place_name: 'Great Wall of China',
      place_intro: 'The Great Wall of China, a marvel of human engineering, stretches over 13,000 miles. Discover its history as a defense barrier and explore its stunning sections amidst picturesque landscapes. A true wonder of the world.',
      photo_count: 92,
      like_count: 78,
      date: '3rd February, 2020',
    },
    {
      story_id: 121,
      id: 111,
      place_name: 'Eiffel Tower',
      place_intro: 'The Eiffel Tower, an iconic symbol of Paris, stands as a testament to architectural marvel. With its intricate iron lattice structure, it offers breathtaking panoramic views of the City of Lights. Explore its rich history and romantic ambiance.',
      photo_count: 38,
      like_count: 27,
      date: '3rd February, 2020',
    },
    {
      story_id: 122,
      id: 112,
      place_name: 'Machu Picchu',
      place_intro: 'Machu Picchu, nestled high in the Andes mountains, is an ancient Inca citadel shrouded in mystery. Wander through its ancient ruins, where llamas roam freely, and soak in the spiritual energy of this UNESCO World Heritage site.',
      photo_count: 72,
      like_count: 60,
      date: '3rd February, 2020',
    },
    {
      story_id: 123,
      id: 113,
      place_name: 'Great Wall of China',
      place_intro: 'The Great Wall of China, a marvel of human engineering, stretches over 13,000 miles. Discover its history as a defense barrier and explore its stunning sections amidst picturesque landscapes. A true wonder of the world.',
      photo_count: 82,
      like_count: 74,
      date: '3rd February, 2020',
    },
    {
      story_id: 124,
      id: 114,
      place_name: 'Santorini',
      place_intro: 'Santorini, a Greek paradise in the Aegean Sea, boasts white-washed buildings perched on cliffs overlooking crystal-clear waters. Explore charming villages, savor local cuisine, and witness captivating sunsets over the caldera.',
      photo_count: 66,
      like_count: 85,
      date: '3rd February, 2020',
    },
    {
      story_id: 125,
      id: 115,
      place_name: 'Pyramids of Giza',
      place_intro: 'The Pyramids of Giza, Egypt\'s ancient wonders, have stood the test of time for over 4,000 years. Marvel at the colossal structures built as tombs for pharaohs and immerse yourself in the mysteries of ancient Egypt.',
      photo_count: 93,
      like_count: 98,
      date: '3rd February, 2020',
    },
  ];

  export default Stories; 